apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: ken-test
  labels:
    name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-server
  template:
    metadata:
      labels:
        name: redis-server
    spec:
      hostname: redis-server
      securityContext:
        fsGroup: 10001
      containers:
        - image: smssit.azurecr.io/rhel8/redis-6:1-92.1669834635
          name: redis-server
          env:
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: redis-server
                  key: redis-password
          volumeMounts:
          - mountPath: /var/lib/redis/data 
            name: data-store
          ports:
            - containerPort: 6379 
              name: tcp
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: redis-data

