apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: sit-nbp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: thin-csi 

