apiVersion: v1
kind: Service
metadata:
  name: redis 
  namespace: sit-nbp 
  labels:
    app: redis-server
spec:
  ports:
    - nodePort: 30159
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: redis-server 
  type: NodePort 

